/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.beans.PropertyVetoException;
import modelo.ConexionBD;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class MDISistemaEjemplo extends javax.swing.JFrame {
    FRMAuto fAuto;
    FRMEstudiante fEstudiante;
    FRMProducto fProducto;
    FRMCliente fCliente;
    FRMProveedor fProveedor;
    FRMVenta fVenta;
    FRMLogin fLogin;
    FRMRol fRol;
    FRMUsuario fUsuario;
    FRMAuditoria fAuditoria;
    

    /**
     * Creates new form MDISistemaEjemplo
     */
    public MDISistemaEjemplo() {
        ConexionBD.getInstance();
        initComponents();
        fAuto = new FRMAuto();
        fEstudiante = new FRMEstudiante();
        fProducto = new RRMProducto();
        fCliente = new FRMCliente();
        fProveedor = new FRMProveedor();
        fVenta = new FRMVenta();
        fLogin = new FRMLogin();
        fRol = new FRMRol();
        fUsuario = new FRMUsuario();
        fAuditoria = new FRMAuditoria();
        
        escritorio.add(fAuto);
        escritorio.add(fEstudiante);
        escritorio.add(fProducto);
        escritorio.add(fCliente);
        escritorio.add(fProveedor);
        escritorio.add(fVenta);
        escritorio.add(fLogin);
        escritorio.add(fRol);
        escritorio.add(fUsuario);
        escritorio.add(fAuditoria);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        MNUAdministrar = new javax.swing.JMenu();
        itemEstudiantes = new javax.swing.JMenuItem();
        itemAuto = new javax.swing.JMenuItem();
        itemUsuario = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MNUAdministrar.setMnemonic('f');
        MNUAdministrar.setText("Administrar");

        itemEstudiantes.setText("Estudiantes");
        itemEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEstudiantesActionPerformed(evt);
            }
        });
        MNUAdministrar.add(itemEstudiantes);

        itemAuto.setMnemonic('o');
        itemAuto.setText("Auto");
        itemAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAutoActionPerformed(evt);
            }
        });
        MNUAdministrar.add(itemAuto);

        itemUsuario.setMnemonic('s');
        itemUsuario.setText("Usuario");
        itemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUsuarioActionPerformed(evt);
            }
        });
        MNUAdministrar.add(itemUsuario);

        itemSalir.setMnemonic('x');
        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        MNUAdministrar.add(itemSalir);

        menuBar.add(MNUAdministrar);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        ConexionBD.desconectar( ) ;
        try  {
            fEstudiante.setClosed(true);
            fAuto.setClosed(true);
            fProducto.setClosed(true);
            fCliente.setClosed (true);
            fProveedor.setClosed(true);
            fVenta.setCloosed(true);
            fLogin.setClosed(true);
            fRol.setClosed(true);
            fUsuario.setClosed(true);
            fAuditoria.setClosed(true);
            
            
            
        } catch (PropertyVetoException ex) {
        System.err.println("Error al salir:"+ex.getMessage());
    }
        System.exit(0);
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEstudiantesActionPerformed
         fEstudiante.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_itemEstudiantesActionPerformed

    private void itemAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAutoActionPerformed
         fAuto.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_itemAutoActionPerformed

    private void itemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsuarioActionPerformed
         fUsuario.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_itemUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDISistemaEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDISistemaEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDISistemaEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDISistemaEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDISistemaEjemplo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MNUAdministrar;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem itemAuto;
    private javax.swing.JMenuItem itemEstudiantes;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuItem itemUsuario;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pasteMenuItem;
    // End of variables declaration//GEN-END:variables

    private static class FRMEstudiante {

        public FRMEstudiante() {
        }
    }

    private static class FRMProducto {

        public FRMProducto() {
        }
    }

}
